config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  devise_for :views
  devise_for :users
  get 'home/index'
  

  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end
  root to: "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers,dependent: :destroy
  validates :title, presence: true, length: {maximum: 140}
  validates :desciption, presence: true, length: {maximum: 600}

  acts_as_likeable

def feed
 	Answer.all.order(created_at: :desc)
end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.new

    # byebug
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers=Answer.all
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id=current_user.id
    # byebug
    respond_to do |format|
      if @question.save
        QuestionMailer.notify_email(current_user).deliver_now

        format.html { redirect_to '/', notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render '/'}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :desciption, :user_id, :anon)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_ans.html.erb
<%if answer.question_id== @question.id%>
  <%= answer.user.email %>
  <%= answer.content %>
  <%if can? :update,answer%>
  <%= link_to 'Edit', edit_answer_path(answer) %> |
  <%end%>
  <%if can? :destroy,answer%>
  <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }%><br>
  <%end%>

<%end%>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desciption %><br>
    <%= f.text_area :desciption %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_ques.html.erb
<div class="userDetail">
  <% if question.anon=="N"%>
  <%= question.user.email %>
  <%else%>

    <%end%>
</div>

<div class="title">
  <%= question.title %>
</div>
<div class="desciption">
  <%= question.desciption %>
</div>
<div class="other">
  <%= link_to('like', question_like_path(question), remote:true,method: :post) %>
</div>

<div class="other">
<%= link_to 'Show', question %>
</div>

app/views/questions/create.js.erb
$('#question').prepend("<%= escape_javascript (render 'questions/index', question: @questions) %>");

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "LOGOUT",destroy_user_session_path, method: :delete %>
<h1>Questions</h1>
<div class="createQuestion">
<%= form_for @questions, remote: true do |f| %>
<%= f.label :title %> <br>
<%= f.text_area :title %>  <br>
<%= f.label :desciption %> <br>
<%= f.text_area :desciption %>  <br>
<%= f.label :anon%>
<%= f.text_area :anon%>
<div class="actions">
<%= f.submit  id: 'create_tweet_submit' %>
<span id="characters">0</span>
</div>
<%end%>
  <div id="question">
    <% current_user.feed.each do |question| %>
      <%= render 'ques',question: question  %>
    <% end %>
  </div>
<br>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @question.desciption %>
</p>

<p>
  <strong>User:</strong>
  <% if @question.anon=="N"%>
  <%= @question.user.email %>
  <%else%>
  <p>
  Anonymous
  </p>
    <%end%>
</p>



  <div id="answer">
    <% @question.feed.each do |answer| %>
      <%= render 'ans',answer: answer  %>
    <% end %>
  </div>






<%if can? :update,@question%>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%end%>
<%if can? :destroy,@question%>
<%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<%= link_to 'Back', questions_path %>
<%= link_to 'New Answer',new_answer_path(:id => @question.id)%>